language: python
dist: xenial

python:
  - 3.6

addons:
  postgresql: "9.6"

env:
  global:
    - PGUSER=postgres

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
  - ./.ci/setup_db.sh
  - nose2 -v
  - ./test/test_pum.sh

deploy:
  provider: script
  script: ./.deploy/deploy_to_pypi.sh
  on:
    tags: true
