site_name: pum documentation

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_signature: true
            show_signature_annotations: true
            separate_signature: true


markdown_extensions:
  - admonition
  - codehilite

nav:
  - Introduction: index.md
  - API:
      - Changelog: api/changelog.md
      - MigrationParameterDefinition: api/migration_parameter_definition.md
      - MigrationParameterType: api/migration_parameter_type.md
      - PumConfig: api/pum_config.md
      - SchemaMigrations: api/schema_migrations.md
      - Upgrader: api/upgrader.md

extra:
  # Remove "Made with Material for MkDocs" from footer
  generator: false
